# Generated by Django 4.1 on 2023-02-06 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_order_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
