# Generated by Django 4.1 on 2023-02-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_test_delete_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='name',
        ),
        migrations.AddField(
            model_name='test',
            name='email',
            field=models.EmailField(default='exit', max_length=50),
            preserve_default=False,
        ),
    ]
