# Generated by Django 4.1 on 2023-02-10 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_register1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
